### ISSUE TITLE
PATH not set on MacOS

### ISSUE THREAD

**Issue by yurimotilev** [castle-engine/castle-engine#393] opened 2022-05-31 12:32 UTC
Castle-editor app (from castle-engine-7.0-alpha.snapshot-darwin-x86_64.zip) cannot find files
![Снимок экрана 2022-05-31 в 15 26 50](https://user-images.githubusercontent.com/104770834/171173182-8bc2883f-688c-4b03-b7b3-9101009974fe.png)
![Снимок экрана 2022-05-31 в 15 27 37](https://user-images.githubusercontent.com/104770834/171173190-f156b341-6808-4523-a0a5-c3322609d9db.png)
.

**Comment by michaliskambi** [comment] 2022-06-01 03:04
Thank you for the report! I'm happy that our recent release for macOS sparked interest :)

Short answer: Get the latest macOS release from https://castle-engine.io/ , run it, and in _"Preferences" -> "General"_ set _"Castle Game Engine path"_ (e.g. to `/Users/XXX/Downloads/castle_game_engine`).

Details:

1. Since today, macOS release of Castle Game Engine is automatically done by Jenkins after each commit and available for download from https://castle-engine.io/ just like for all other platforms.

    Aside from this issue, I already made a few other macOS-specific fixes :) And extended https://castle-engine.io/macos a bit.

2. Both problems you show have the same culprit: CGE editor didn't find the CGE own path. In effect `CastleEnginePath` is empty, and packages are compiled using relative path (which cannot find `src/vampyre....lpk`) and build tool cannot be found in CGE bin/ subdirectory.

    The culprit is Apple "translocation". When the application is detected as being run from a zip file, downloaded from the Internet, the CGE editor cannot find the CGE location, because macOS actually moved the application to a random location. I can reproduce it, logs show indeed:

    ```
    Warning: Castle Game Engine directory cannot be detected:
    - $CASTLE_ENGINE_PATH environment variable not defined, or points to an incorrect directory.
    - Moreover we cannot find Castle Game Engine looking at parent directory of this program exe.
    Path: Program data path detected as "file:///private/var/folders/hg/9p_2cnfn595_rzzhqlvbds4c0000gn/T/AppTranslocation/A3AAA105-D32C-4875-B56E-D59CD9EC0F4D/d/castle-editor.app/Contents/Resources/data/"
    ```

    Above, Apple moved application from `~/Downloads/castle_game_engine/bin/castle-editor.app` -> `/private/var/folders/hg/9p_2cnfn595_rzzhqlvbds4c0000gn/T/AppTranslocation/A3AAA105-D32C-4875-B56E-D59CD9EC0F4D/d/castle-editor.app` .

    There are some hacky solutions: https://www.synack.com/blog/untranslocating-apps/

    There is a proper solution, but it will take time: we should just package *whole* Castle Game Engine into one big application bundle. So the CGE zip should really just contain one application, `Castle Game Engine.app`, instead of subdirectories, with editor in `bin/castle-editor.app`. I planned this already, but it will take time.

    The current solution is just to enable you to manually set CGE path, thus workarounding the fact that editor cannot detect CGE path automatically. We make clear warning if CGE path seems incorrect in the main window, and allow to customize it from "Preferences", running basic checks whether the chosen directory is good. This is in general a good "reliability improvement" to the engine, on all platforms.

I'm closing this (do let me know whether the solution works :), and reopen this issue if it persists).

Solving this properly, by packaging *whole* Castle Game Engine into one big application bundle, is recorded on the roadmap - https://castle-engine.io/roadmap#_macos_package_engine_as_one_big_application_bundle .

**Closed by michaliskambi** 2022-06-01 03:04 UTC

**Comment by yurimotilev** [comment] 2022-06-01 06:23
Thanks, worked now! But there is another 'micro problem' with Apple Gatekeeper. I solved this by 'sudo xattr -rd com.apple.quarantine ...' for all in CGE/bin, but this is not the right way. Must I create new issue?

**Comment by michaliskambi** [comment] 2022-06-01 13:44
> Thanks, worked now! But there is another 'micro problem' with Apple Gatekeeper. I solved this by 'sudo xattr -rd com.apple.quarantine ...' for all in CGE/bin, but this is not the right way. Must I create new issue?

You mean the fact that you cannot run unsigned application on macOS? From what I understand, this is Gatekeeper role ( https://support.apple.com/pl-pl/guide/security/sec5599b66df/web https://en.wikipedia.org/wiki/Gatekeeper_(macOS) ) and indeed we're affected, as our app bundle is not signed.

You don't need to use command-line for this, you can just right-cilck on the application, choose "Open" and then you can allow running unsigned application.

This is documented on https://castle-engine.io/macos .

I added a TODO about it to the roadmap, https://castle-engine.io/roadmap#_macos_have_signed_app_bundle_for_the_editor . Indeed we need to deal with this to really have natural experience for users on macOS.
