### ISSUE TITLE
Space block

### ISSUE THREAD

**Issue by teadom** [castle-engine/castle-engine#107] opened 2019-01-22 16:17 UTC
Ubuntu 18.04, Castle engine 6.4 (fp-units-castle-game-engine 6.4+dfsg1-2)

With the following code:

{$mode objfpc}{$H+}

uses CastleWindow, SysUtils, CastleGLImages, CastleFilesUtils, CastleKeysMouse;
var
    Window: TCastleWindow;
    Image: TGLImage;
    X: Single = 0.0;
    Y: Single = 0.0;

procedure WindowRender(Container: TUIContainer);
begin
    Image.Draw(X, Y);
end;

procedure WindowPress(Container: TUIContainer; const Event: TInputPressRelease);
begin
    if Event.IsKey(K_Space) then
        X := -440;
end;

procedure WindowUpdate(Container: TUIContainer);
var
    SecondsPassed: Single;
begin
    SecondsPassed := Container.Fps.SecondsPassed;
    X := X + SecondsPassed * 300;
    if Container.Pressed[K_Up] then
        Y := Y + SecondsPassed * 100;
    if Container.Pressed[K_Down] then
        Y := Y - SecondsPassed * 100;
    if X > 1600 then
        X := -440;
    if (Y > 600) then
        Y := 600;
    if (-10 > Y) then
        Y := -10;
end;

begin
    Image := TGLImage.Create(ApplicationData('bugship.png'));
    try
        Window := TCastleWindow.Create(Application);
        Window.OnRender := @WindowRender;
        Window.OnUpdate := @WindowUpdate;
        Window.OnPress  := @WindowPress;
        Window.Open;
        Application.Run;
    finally FreeAndNil(Image) end;
end.

![bugship](https://user-images.githubusercontent.com/46931578/51546736-dd0af300-1e75-11e9-8ebe-922cd3fa45e2.png)

When I press K_Up or K_Down or K_Left or K_Right and then press K_Space it does nothing first time. And it literally only K_Space that does so.

**Comment by michaliskambi** [comment] 2019-01-22 16:31
Indeed, it's a problem in this example code. Solution for Castle Game Engine 6.4:

- Use TCastleWindowCustom instead of TCastleWindow

- And at the beginning (after `Window.Open`) add a code

```
Background := TCastleRectangleControl.Create(Application);
Background.FullSize := true;
// Background.Color := ... adjust as you wish, the default in black, color constants are in CastleColors unit
Window.Controls.Add(Background);
```

- and declare `Background: TCastleRectangleControl` variable somewhere above.
- Also add `CastleControls` to the uses clause, to have TCastleRectangleControl defined.

In the unstable Castle Game Engine 6.5 (from GitHub https://github.com/castle-engine/castle-engine/ ), that should be really soon released as 6.6, the solution is simpler:

- Just use TCastleWindowBase (TCastleWindowCustom is only a deprecated alias for  TCastleWindowBase) instead of TCastleWindow. That's it, it automatically has a background, configurable in Window.Container.BackgroundColor.

CGE 6.6 should be released *really soon*, at that point the code on the webpage will be updated to just use TCastleWindowBase :)

The reason: 

- TCastleWindow creates a default scene manager, with a default camera, that handles the space key and arrow keys. The scene manager remains empty in this example, so the problem isn't visible, but the camera still processes keys. Usually this is not a problem, but if you use arrow keys then camera thinks you want to rotate the scene, and then pressing "space" stops this rotation and marks the "space" key as "already handled". 

- Using TCastleWindowCustom is the best solution here, it avoids the whole "default scene manager with default camera", which you really don't want in this case.

- In CGE 6.4, the default background of TCastleWindowCustom is undefined, hence the need for Background.

**Closed by michaliskambi** 2019-01-22 16:31 UTC
