### ISSUE TITLE
Don't use special characters in documentation web pages titles?

### ISSUE THREAD

**Issue by eugeneloza** [castle-engine/castle-engine#35] opened 2016-11-09 13:53 UTC
Maybe it'd be a good idea not to use special (logical operations or system) characters like "|", ":", "/", "*", ">", etc. in web pages titles? E.g.
> "Sound | Tutorial | Castle Game Engine.html"

It saves perfectly in Linux (thanks to UTF8), but then the saved file can't be acessed (renamed/deleted/opened) in Windows :) Firefox automatically replaces these characters, but only if save procedure was made in Windows. On Linux it doesn't replace anything.
Maybe something like
> "Sound - Tutorial - Castle Game Engine.html"

might be better?

**Comment by michaliskambi** [comment] 2016-11-10 01:26
I don't think we should do it... Because:

1. The problem affects a lot of webpages. Looking at various CMSes, and various popular sites:

  - https://wordpress.com/pricing/ , http://drupal.com/get-started-with-drupal , https://developer.android.com/studio/index.html (use the "|")
  - https://github.com/castle-engine/castle-engine, https://en.wikipedia.org/wiki/Wikipedia:Introduction (use the ":")
  - This very bugreport: https://github.com/castle-engine/castle-engine/issues/35 uses apostrophe and "?". (Although these special characters came from user-provided title, but still the GitHub programmers did not code anything to "sanitize" these characters in the page &lt;title&gt;.)

2. The problem affects any software running on Linux. If your Windows (FAT or NTFS) disk driver doesn't protect you, then you have many ways to create a filename of a Windows partition that will not be acceptable to Windows programs.

  Sometimes the problem is actually limited to the Windows standard file manager (explorer), and you can rename files using command-line, e.g. Cygwin tools.

3. This indicates that the right place to solve it is the disk driver. Something that would prevent creating invalid filenames through any means, which means: something at the kernel level. So the disk driver for FAT or NTFS.

  They should disallow creating files with invalid characters. Just like they should disallow creating files that ignore the "case-insensitive" rule (so you should not be able to create "foo" alongside "FOO" on a FAT partition).

  This is actually implemented in ntfs-3d (latest driver used at least on Ubuntu by default to access NTFS filesystems), it's just not activated by default. See http://www.tuxera.com/community/ntfs-3g-manual/#4 , and see https://help.ubuntu.com/community/MountingWindowsPartitions . The last page shows an example how to make it work: create the mount directory manually, and add a line like

  ~~~~
  UUID=xxx  /media/yyy  ntfs-3g  defaults,windows_names,locale=en_US.utf8  0 0
  ~~~~

  to the /etc/fstab. See https://help.ubuntu.com/community/MountingWindowsPartitions , section "Manual Configuration" explains the process in details. I use this approach too.

  I vaguely remember that for FAT filesystems there was some option for this too. Reading https://www.kernel.org/doc/Documentation/filesystems/vfat.txt , there's at least check= option to check case-insensitivity. Maybe it's disallowing invalid chars by default? I do not have a FAT partition here to test it.

Summary:

- As the problem affects a lot of webpages, and actually a lot of sofware besides web browsers, it seems reasonable that it should be fixed at the ntfs-3d driver level. Maybe it should by default use 'windows_names' option? Or maybe Ubuntu should by default use windows_names?

  There is a bugreport in Ubuntu that ends with exactly this conclusion: https://bugs.launchpad.net/ubuntu/+source/ntfs-3g/+bug/230906 .

- Trying to avoid/workaround this on our end (in our website) seems like more trouble than it is worth. We would have to change quite a few of our &lt;titles&gt;, and watch for the bad characters in the future. And it seems that websites much bigger than ours don't do it.

**Closed** 2016-11-10 01:26 UTC
Labels: question
