### ISSUE TITLE
crash on strategy_game_demo demo

### ISSUE THREAD

**Issue by codz01** [castle-engine/castle-engine#309] opened 2021-06-24 11:03 UTC
Hi
i am using latest fpc & lazarus trunk  for win32 
and latest master branch castle game engine (downloaded yesterday)
i get a crash in examples\tiled\strategy_game_demo 
any idea whats wrong ? 
![zubUXbWAKp](https://user-images.githubusercontent.com/10813427/123252239-96ed6a00-d4db-11eb-8758-59e0ea1f7800.gif)

**Comment by eugeneloza** [comment] 2021-06-24 11:51
Just tested - works for me on Win64 with latest CGE version and a few months obsolete Trunk FPC/Lazarus version.

Can you try checking out C:\Users\(username)\AppData\Local\strategy_game_demo\strategy_game_demo.log file? It doesn't seem to be too verbose, but may still contain more accurate reason for the crash.

**Comment by peardox** [comment] 2021-06-24 12:13
Just tried ARM32 - fine there too

**Comment by codz01** [comment] 2021-06-26 22:08
the log file 
Log for "strategy_game_demo".
  Version: 0.1.
  Started on 2021-06-24 at 11:55:54.
  Castle Game Engine version: 7.0-alpha.snapshot (unstable).
  Compiled with FPC 3.2.2.
  Platform: Desktop, OS: Win32, CPU: i386 (32-bit).
LibPng not found. We will use slower FPImage to load PNG format.
WinAPI: Dots (pixels) per inch is 96.00 (1.00 * default 96.00)
-------------------- Rendering Context Initialization begin
OpenGL information (detected by strategy_game_demo):

--------
Version:
  Version string: 3.3.0
  Version parsed: major: 3, minor: 3, release exists: True, release: 0, vendor-specific information: ""
  Vendor-specific version parsed: major: 0, minor: 0, release: 0
  Vendor: NVIDIA Corporation
  Vendor type: Nvidia

  Renderer: Quadro FX 1600M/PCIe/SSE2
  Fglrx (ATI on Linux): False
  Mesa: False

  Buggy glGenerateMipmap(EXT): False
  Buggy GL_LIGHT_MODEL_TWO_SIDE: False
  Buggy VBO: False
  Buggy shader shadow map: False
  Buggy FBO rendering to multi-sampling texture: False
  Buggy FBO rendering to cube map texture: False
  Buggy swap buffers with non-standard glViewport: False
  Buggy 32-bit depth buffer: False
  Buggy GLSL gl_FrontFacing: False
  Buggy GLSL read varying: False
  Buggy Pure Shader Pipeline: False
  Buggy Texture Size Above 2048: False

------------------------
Real versions available:
(checks both version string and actual functions availability in GL library, to secure from buggy implementations)

  1.2: True
  1.3: True
  1.4: True
  1.5: True
  2.0: True
  2.1: True
  3.0: True
  3.1: True
  3.2: True
  3.3: True
  4.0: False

---------
Features:
  Shaders (GLSL) support: Standard
  => Enable deprecated (fixed-function) support: False
  Multi-texturing: True
  Framebuffer Object: Standard (or ARB "core extension")
  Multi-sampling for FBO buffers and textures: True
  Vertex Buffer Object: True
  GenerateMipmap available (and reliable): True
  Cube map textures: Standard
  Compressed textures supported: [DXT1_RGB, DXT1_RGBA, DXT3, DXT5]
  3D textures: Standard
  Textures non-power-of-2: True
  Blend constant parameter: True
  Float textures: True
  Depth textures: True
  Packed depth + stencil: True

  All extensions: GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_blend_func_extended GL_ARB_clear_buffer_object GL_ARB_color_buffer_float GL_ARB_compatibility GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_draw_buffers GL_ARB_draw_elements_base_vertex GL_ARB_draw_instanced GL_ARB_enhanced_layouts GL_ARB_ES2_compatibility GL_ARB_ES3_compatibility GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_layer_viewport GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_geometry_shader4 GL_ARB_get_program_binary GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_imaging GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_occlusion_query2 GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_program_interface_query GL_ARB_provoking_vertex GL_ARB_robust_buffer_access_behavior GL_ARB_robustness GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_separate_shader_objects GL_ARB_shader_bit_encoding GL_ARB_shader_objects GL_ARB_shader_texture_lod GL_ARB_shading_language_100 GL_ARB_shading_language_420pack GL_ARB_shading_language_include GL_ARB_shading_language_packing GL_ARB_shadow GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_texture_border_clamp GL_ARB_texture_buffer_object GL_ARB_texture_buffer_range GL_ARB_texture_compression GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_float GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_mirrored_repeat GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_stencil8 GL_ARB_texture_storage GL_ARB_texture_storage_multisample GL_ARB_texture_swizzle GL_ARB_texture_view GL_ARB_timer_query GL_ARB_transpose_matrix GL_ARB_uniform_buffer_object GL_ARB_vertex_array_bgra GL_ARB_vertex_array_object GL_ARB_vertex_attrib_binding GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_vertex_type_10f_11f_11f_rev GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_ARB_window_pos GL_ATI_draw_buffers GL_ATI_texture_float GL_ATI_texture_mirror_once GL_S3_s3tc GL_EXT_texture_env_add GL_EXT_abgr GL_EXT_bgra GL_EXT_bindable_uniform GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_compiled_vertex_array GL_EXT_Cg_shader GL_EXT_depth_bounds_test GL_EXT_direct_state_access GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_draw_range_elements GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXTX_framebuffer_mixed_formats GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_geometry_shader4 GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_multi_draw_arrays GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_packed_pixels GL_EXT_pixel_buffer_object GL_EXT_point_parameters GL_EXT_provoking_vertex GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_separate_shader_objects GL_EXT_separate_specular_color GL_EXT_shader_integer_mix GL_EXT_shadow_funcs GL_EXT_stencil_two_side GL_EXT_stencil_wrap GL_EXT_texture3D GL_EXT_texture_array GL_EXT_texture_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_latc GL_EXT_texture_compression_rgtc GL_EXT_texture_compression_s3tc GL_EXT_texture_cube_map GL_EXT_texture_edge_clamp GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_lod GL_EXT_texture_lod_bias GL_EXT_texture_mirror_clamp GL_EXT_texture_object GL_EXT_texture_shared_exponent GL_EXT_texture_sRGB GL_EXT_texture_sRGB_decode GL_EXT_texture_storage GL_EXT_texture_swizzle GL_EXT_timer_query GL_EXT_vertex_array GL_EXT_vertex_array_bgra GL_EXT_import_sync_object GL_IBM_rasterpos_clip GL_IBM_texture_mirrored_repeat GL_KHR_debug GL_KTX_buffer_region GL_NV_blend_square GL_NV_conditional_render GL_NV_copy_depth_to_color GL_NV_copy_image GL_NV_depth_buffer_float GL_NV_depth_clamp GL_NV_ES1_1_compatibility GL_NV_explicit_multisample GL_NV_fence GL_NV_float_buffer GL_NV_fog_distance GL_NV_fragment_program GL_NV_fragment_program_option GL_NV_fragment_program2 GL_NV_framebuffer_multisample_coverage GL_NV_geometry_shader4 GL_NV_gpu_program4 GL_NV_half_float GL_NV_light_max_exponent GL_NV_multisample_coverage GL_NV_multisample_filter_hint GL_NV_occlusion_query GL_NV_packed_depth_stencil GL_NV_parameter_buffer_object GL_NV_parameter_buffer_object2 GL_NV_path_rendering GL_NV_pixel_data_range GL_NV_point_sprite GL_NV_primitive_restart GL_NV_register_combiners GL_NV_register_combiners2 GL_NV_shader_buffer_load GL_NV_texgen_reflection GL_NV_texture_barrier GL_NV_texture_compression_vtc GL_NV_texture_env_combine4 GL_NV_texture_expand_normal GL_NV_texture_multisample GL_NV_texture_rectangle GL_NV_texture_shader GL_NV_texture_shader2 GL_NV_texture_shader3 GL_NV_transform_feedback GL_NV_vertex_array_range GL_NV_vertex_array_range2 GL_NV_vertex_buffer_unified_memory GL_NV_vertex_program GL_NV_vertex_program1_1 GL_NV_vertex_program2 GL_NV_vertex_program2_option GL_NV_vertex_program3 GL_NVX_conditional_render GL_NVX_gpu_memory_info GL_SGIS_generate_mipmap GL_SGIS_texture_lod GL_SGIX_depth_texture GL_SGIX_shadow GL_SUN_slice_accum GL_WIN_swap_hint WGL_EXT_swap_control 

---------------------------
Current buffers bit depths:
  Color (red / green / blue / alpha): 8 / 8 / 8 / 0
  Depth: 24
  Index: 0
  Stencil: 0
  Accumulation (red / green / blue / alpha): 16 / 16 / 16 / 16
  Double buffer: True
  Multi-sampling (full-screen anti-aliasing) possible: True
    Current: 1 samples per pixel

-------------
Stack depths:
  Attributes: 16
  Client attributes: 16
  Modelview: 32
  Projection: 4
  Texture: 10
  Name: 128

-------
Limits:
  Max clip planes: 8
  Max lights (fixed-function limit): 8
  Max eval order: 8
  Max list nesting: 64
  Max pixel map table: 65536
  Max texture size: 8192
  Max viewport dims (width, height): 8192 8192
  Max texture units (shader pipeline): 32
  Max texture units (fixed-function): 4
  Max cube map texture size: 8192
  Max 3d texture size: 2048
  Max texture max anisotropy: 16
  Query counter bits (for occlusion query): 32
  Max renderbuffer size: 8192

-------
Memory (in Kb):
  Total: 524288
  Current: 494120
  Current for VBO: 0 (unknown)
  Current for Textures: 0 (unknown)
  Current for Renderbuffers: 0 (unknown)
-------------------- Rendering Context Initialization end
Path: Program data path detected as "file:///D:/FPC/libs/castle-engine-master/examples/tiled/strategy_game_demo/data/"
Exception: Exception "EConvertError":
"" is an invalid integer

  $00436A8F
  $0077F642
  $00780C14
  $00781BB7
  $007816C9
  $00781D99
  $00781ECD
  $00783450
  $007760B6
  $00775C7A
  $00775BBC
  $00417F57
  $00417CE5
  $004178D6
  $77B186EF
  $77B18876
  $77B143CF

**Comment by codz01** [comment] 2021-06-26 22:17
after rebuild with debug enabled , this is where it stops
![cge](https://user-images.githubusercontent.com/10813427/123527106-51dc5a00-d6cc-11eb-9eaf-42c8f1bcfb5b.png)

**Comment by michaliskambi** [comment] 2021-06-27 00:08
Hm, it's interesting -- we **had** a bug that could exhibit in exactly the way you describe:  

- `EConvertError` exception, at loading Tiled map (which happens when strategy_game_demo does `MapControl.URL := ...`). 
- And it would be reproducible only on systems where default `DecimalSeparator` is not a dot (which made it hard to reproduce, as it depends both on OS and on locale).
- And even on affected systems, it wasn't reproducible in all demos, as usually `CastleUtils` initialization sets `DecimalSeparator` to dot. The bug occurs only when something else sets it later to locale-specific char -- I never debugged it to the end (as the right solution was to not depend on global `DecimalSeparator` value anyway), but it seems in case of strategy_game_demo the `SysUtils` initialization overrides it.

Aaaand the bug was fixed in https://github.com/castle-engine/castle-engine/commit/895bcc5e436c11901907ed3baaf69495e362ee92 (and the fix should work regardless of unit initialization order, so regardless of FPC version too). Almost a year ago -- Aug 9, 2020.

Can you check that you definitely use the latest CGE master? 

- Is `D:/FPC/libs/castle-engine-master/` the latest CGE master? 

- If you look at `castle_base` package location in Lazarus "Package -> Open Loaded Package..." (see screenshot) does the "Filename" at the bottom point to where you have latest CGE master? Maybe you downloaded latest CGE master recently, but Lazarus uses `castle_base` package from some ancient location.

![Zrzut ekranu z 2021-06-27 02-00-19](https://user-images.githubusercontent.com/1076978/123528926-f5893280-d6eb-11eb-9209-fc1d4549a090.png)

Unfortunately our version number `7.0-alpha.snapshot (unstable)` (from your log) doesn't pinpoint the engine last commit date. We add the GIT hash to that version number, but only when building "binary + source" engine version to download from zip on https://castle-engine.io/ . If you get the engine source code from GitHub, the GIT hash is not visible in the log, and unfortunately our number `7.0-alpha.snapshot` spans a long time now.

> LibPng not found. We will use slower FPImage to load PNG format.

( Unrelated thing to this issue, just noticed it in the log. ) It means you don't have libpng dll at the exe location. The simplest solution is to compile from CGE editor , https://castle-engine.io/manual_editor.php , at least once -- it will copy the DLL files alongside exe. It will make PNG loading much faster.

**Comment by codz01** [comment] 2021-06-27 04:44
Hi michaliskambi 
i've checked the path , yes it shows i'am using the latest CGE 
![Uploading cge2.png…]()
i've checked castle-engine-master\examples\images_videos\image_convert.lpr to see if it matches the commit 895bcc5 , and yes it use StrToFloatDot function

also i've add libpng dll to the exe location , but still the same error

**Closed** 2021-06-28 00:33 UTC
Labels: pending feedback

**Comment by michaliskambi** [comment] 2021-06-28 00:35
Fixed, thanks for reporting!

Background:

For some reason (maybe FPC compiler bug? I reproduced with FPC 3.2.0, previous stable) on Win32, the assumption at one place "AnsiString is alwas terminated by #0" was broken. It all worked OK on Linux/x86_64 and Windows/x86_64, failure was only on Win32 (Windows/i386).

The code was convoluted and using PChar, so I don't eliminate the possibility it was our bug and we depended on something that wasn't really guaranteed.

As part of the fix, I refactored that to be much simpler. (in https://github.com/castle-engine/castle-engine/commit/e0afbaa921773bbbce176e23170f3bc333408818 , https://github.com/castle-engine/castle-engine/commit/34ca620eeab47aece515b89e8e445290f463b668 ).

Note: Compiling in debug mode using CGE build tool (`castle-engine --os=win32 --cpu=i386 compile --mode=debug`) I got a full backtrace. The error was at `StrToDWord`, and as the message says, it's because it was called with argument = '' (empty string). I actually tested "running on Windows" using `wine` and `win64` on Linux, I assume it is OK -- as it reproduced the bug before fixing.

My previous suspicion that this is related to `DecimalSeparator` and https://github.com/castle-engine/castle-engine/commit/895bcc5e436c11901907ed3baaf69495e362ee92 was completely invalid -- this issue was at `StrToDWord`, and completely unrelated :)

**Comment by codz01** [comment] 2021-06-28 11:58
thanks , it works now 
i have a crash on  examples\tiled\map_viewer\ demo , but only when i load ( orthogonal-outside.tmx ) file , other files works fine 
![abvjIq1U10](https://user-images.githubusercontent.com/10813427/123632944-1181f680-d808-11eb-861a-3d769753d3b1.gif)

**Comment by michaliskambi** [comment] 2021-06-28 19:32
> i have a crash on examples\tiled\map_viewer\ demo , but only when i load ( orthogonal-outside.tmx ) file , other files works fine

Thank you for testing! I fixed this one too.

I also added to testsuite (automatically run by Jenkins) to open a bunch of Tiled files, so we automatically verify that opening them all works OK, and can easily check that it all works on win32 too.
