### ISSUE TITLE
Shadow maps bug

### ISSUE THREAD

**Issue by eugeneloza** [castle-engine/castle-engine#6] opened 2015-10-31 07:51 UTC
A rare bug (and therefore absolutely non-critical) with ShadowMaps. At some angles a few distant objects might become visible through invisible ones. This only happens at near-screen-edge angles (never in front) and extremely rarely.
![cge_shadows_error](https://cloud.githubusercontent.com/assets/10726162/10862532/7fc69f04-7fb4-11e5-80d7-7036ca3f8ce9.jpg)
P.S. This might be bug with my specific videocard (Radeon 5400) as seldomly it shows different bugs in different games. So I'll test it deeper when I completely switch to ShadowMaps.

**Comment by michaliskambi** [comment] 2015-10-31 22:31
Are you sure it's related to shadow maps? It never happens without shadow maps?

I'm asking, because normally such things may happen if the depth buffer precision is too low to cover the distances between near and far planes. It's unrelated to shadow maps.

- Can you see what depth buffer bits do you get? Use glGetInteger(GL_DEPTH_BITS) from CastleGLUtils unit (GL_DEPTH_BITS is constant in GL unit). If you have only 16, try setting Window.DepthBits := 24 before doing Window.Open, and check does your glGetInteger(GL_DEPTH_BITS) increased.

- Try making your near-far range smaller, by increasing the near plane or decreasing the far plane.

- To increase the near plane, increase the 1st float (camera radius) of NavigationInfo.avatarSize . The "near plane" is set by our engine to half of the camera radius. See http://castle-engine.sourceforge.net/x3d_implementation_navigation.php and http://www.web3d.org/documents/specifications/19775-1/V3.2/Part01/components/navigation.html#NavigationInfo

- To decrease the far range: set SceneManager.ShadowVolumes := false (otherwise, shadow volumes implementation forces infinite far plane, although it should not hurt much) and then set NavigationInfo.visibilityLimit.

**Comment by michaliskambi** [comment] 2016-03-29 03:40
I just saw this issue remains unanswered:) Is this still a bug you can reproduce? Can you try one of the suggestions in my comment above --- as I suspect what you saw was not related to shadow maps, but to depth buffer precision?

**Comment by eugeneloza** [comment] 2016-03-30 09:06
Sorry for the delay, I didn't try anything related yet. Just turned off shadowmaps for the time being (and yes, with window.shadowmaps:=false I never see this bug)...
I just found my 3D graphics knowledge to low to work with lights efficiently at the moment (first of all, I still don't understand the way shaders and OpenGL routines work) and started working on interface. I'll try everything as soon as I will return back to lights/shaders issue (maybe in half-a-year or so). Practically I think this issue may be closed or ignored for now. As soon as I will test everything, I'll post the results here.
It also might happen that there will be no more such issues due to hiding/removing of off-screen elements of the maze in the current implementation of Mazer (and Decoherence later).

**Comment by michaliskambi** [comment] 2016-10-05 02:54
I will close this issue for now, as it seems we cannot reproduce the problem:) Please reopen if it will become visible again!

**Closed by michaliskambi** 2016-10-05 02:54 UTC

**Comment by eugeneloza** [comment] 2016-10-05 04:30
Agreed.
Moreover, that might have been a bug of my videocard as I've described at sourceforge.
If I'll ever happen anything like that again, I'll try to 'catch' it...
