### ISSUE TITLE
Tiled map incorrect rendering 

### ISSUE THREAD

**Issue by bbrtj** [castle-engine/castle-engine#567] opened 2024-02-04 15:32 UTC
I've got a problem with tiled map, it renders like this:
![image](https://github.com/castle-engine/castle-engine/assets/44323413/5157f6f7-db34-441e-a5ce-7c6cb6035922)
In tiled, this spot looks like this:
![image](https://github.com/castle-engine/castle-engine/assets/44323413/4f092bbb-e32c-4bab-aeb6-a183f747824a)

Seems like the layers don't have the same Z as in tiled. It worked fine until recently, started happening after the update. Here is the map: https://github.com/bbrtj/perl-mmo-game/blob/master/assets/locations/peril_harbor.tmx. Tiles are in the parent directory.

**Comment by michaliskambi** [comment] 2024-02-05 22:18
I tested with latest CGE on Linux/x86_64 (real machine, with Nvidia) and FreeBSD 14/x86_64 (in VirtualBox), and the rendering result seems fine.

( I tested on FreeBSD as I know you often use FreeBSD. )

Linux:

![obraz](https://github.com/castle-engine/castle-engine/assets/1076978/0ff555e8-62db-4b6c-824b-c53e9120b4b9)

FreeBSD, same:

![obraz](https://github.com/castle-engine/castle-engine/assets/1076978/dee92e90-ecff-4164-9558-cad521d6b579)

This matches your correct screen, from Tiled, from what  I see.

I'm testing using `examples/tiled/map_viewer` from CGE. Just opened your map using "Open Map", didn't change any settings, only panned and zoomed the map for the screenshot. Using FPC 3.2.2.

So -- I cannot reproduce the problem I'm afraid. I need more information:

First of all, can you reproduce the problem on your machine with `examples/tiled/map_viewer`, unmodified? 

- If no, they I will need additional information, preferably a testcase (complete code and data) -- how do you view the map? Should I follow the README in your repo and run the `client` from https://github.com/bbrtj/perl-mmo-game/ ?
    
- If yes (you see the problem even with `examples/tiled/map_viewer`) then something must be different in our environments. Please send the exact FPC version you use, OS, architecture, make sure you use the latest CGE from https://castle-engine.io/download (or just latest GitHub commit), and please write what GPU you have. You can get most of this info using CGE editor, open any project, and use "Help -> System Information", then button "Save To File...".

Thank you!

**Comment by bbrtj** [comment] 2024-02-07 11:55
The map looks fine from the map_viewer example, but it still looks wrong in my actual project. Any tips what might be wrong? I'm loading the map dynamically by changing the URL. I'm looking at it at 90 degree angle, and it was working fine before I deleted the project and set it up again + updated the engine.

All the code is in the repository, but you can't see it unless you set up a game server, so you won't be able to reproduce it yourself currently. Here's where I'm setting the map, nothing special really: https://github.com/bbrtj/perl-mmo-game/blob/master/client/code/views/gameviewplay.pas#L101. The view with the map is not visible while the URL is set, the other "loading" view is visible until everything is ready: https://github.com/bbrtj/perl-mmo-game/blob/master/client/code/views/gameviewloading.pas#L68.

Thank you.

**Comment by michaliskambi** [comment] 2024-02-07 12:51
OK, so we know it has to be something specific to the project.

I looked at the code, you're not doing anything suspicious for my eyes. 

I see in the design ( https://github.com/bbrtj/perl-mmo-game/blob/master/client/data/gameviewplay.castle-user-interface ) you set `SmoothScaling` and `ForceTilesetSpacing` to both `true`, which is totally correct. To be sure, I modified map_viewer to also do this, and the map still looks OK for me.

I tested in CGE editor, opening the project in https://github.com/bbrtj/perl-mmo-game/tree/master/client , with custom editor, and then opening the `gameviewplay` design in editor, and setting `Board` URL in editor to point to `peril_harbor.tmx` (it's outside of the project data, so my URL is `file:///home/michalis/sources/castle-engine/perl-mmo-game/assets/locations/peril_harbor.tmx`, but for local testing this is good). And things look still OK. 

Looking through `PlayerCamera` is OK -- I adjusted the orthographic `Height` of it. Once I adjusted `PlayerCamera` height and position, I also did "Viewport -> Align View to Camera" to also adjust in the viewport camera to be orthographic and with desired height, and now both cameras (`PlayerCamera` and the design-time camera in editor) show OK.

![obraz](https://github.com/castle-engine/castle-engine/assets/1076978/665fcc34-93d2-4d99-825d-c0f806f0367e)

So, I cannot reproduce the issue for now. But I still did not actually run the project. Let me know if I should just follow instructions on https://github.com/bbrtj/perl-mmo-game/tree/master and run it along with the server -- if the instructions in your README are OK, I can do it on my system :)

**Comment by bbrtj** [comment] 2024-02-08 07:41
Thank you for taking a look. I don't think you should set up the server - there are a lot of dependencies (perl 5.38, redis, postgresql, a lot of perl modules). Give me a couple of days, I'll set it up on my VPS when I find some time. You'll then be able to just modify the IP/port of the server and connect to it.

I hope it's not just some artifact that's breaking it - I did Run -> Clean a couple of times to make sure.

**Comment by bbrtj** [comment] 2024-02-11 11:18
I managed to set the server up, it should be running at bbrtj.eu port 1337. It's set in the client in `gamenetwork.pas`. If it doesn't, hit me up on discord - a process may just die so I have to restart (it's quite fragite at the moment).

To properly run the program you will also need some lore, translations etc. which are normally copied over and adjusted by scripts. These scripts currently require the same setup as the server (work in progress :smile:), so you will have to unpack this archive in client data directory instead: 
[data.tar.gz](https://github.com/castle-engine/castle-engine/files/14232095/data.tar.gz)

(the actual map used by the client is also in this package, you can verify if it looks ok with other tools - I have no issue viewing it correctly in tiled)

**Comment by michaliskambi** [comment] 2024-02-12 13:09
I'm closing the issue --- following AD 1 above, this should be fixed in your code, to not scale to exact Z = 0.  Hopefully the above long comment was a helpful explanation :) 

Feel free to talk here more if this is unclear, or not possible to reasonably solve in your code. We can always talk more looking at alternative solutions :) E.g. we plan to have additional way to choose "layer" (which I mentioned briefly above as "you can make 2nd viewport"). We want to extend existing `TCastleTransform.RenderLayer` ( https://castle-engine.io/apidoc/html/CastleTransform.TCastleTransform.html#RenderLayer ) to be an integer and this way enable to easily organize things in layers, in a single viewport, without the need to mess with Z values. If needed, I could look into it sooner.

**Closed by michaliskambi** 2024-02-12 13:09 UTC
Labels: pending feedback

**Comment by bbrtj** [comment] 2024-02-12 13:11
Thank you very much, I will try adjusting the code as you suggested :)
