### ISSUE TITLE
Delphi Leak Test

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#542] opened 2023-10-18 14:59 UTC
https://github.com/peardox/LeakTest.git

Unit1.pas - the defines at the top define what happens (it's simple though)

usex3d will switch between c3d and gltf models

The x3d model has more leaks

If a TCastleControl is dropped on a blank project it will result in the same Leak report as loading a gltf (so the GLTF ain't leaking from the look of it but TCastleControl is)

Leak Reporting is controlled by the line `ReportMemoryLeaksOnShutdown := DebugHook <> 0;` in LeakTest.dpr (use it as an example of doing the same to any project)

NOTE - the Leak Report will only be displayed if the project is run with a Debugger (DebugHook <>0)

**Comment by michaliskambi** [comment] 2023-11-27 00:07
Status:

1. TUnicodeCharEqualityComparer leak was fixed (this was ordinary CGE bug)

2. We have a VCL-specific bug (we seem to never realize that OpenGL context is destroyed, so we never run ApplicationProperties.OnGLContextClose, so in consequence we never free some stuff).

    - Note: This is VCL-only, from what I can tell. It is reproducible with `examples/delphi/vcl` (just added `ReportMemoryLeaksOnShutdown := True` to dpr), while the analogous FMX example `examples/delphi/fmx` reports no leaks.

3. https://github.com/peardox/LeakTest by default (without `usex3d`) makes no memory leaks for me now

    - Which leads me to conclude that TUnicodeCharEqualityComparer was the only leak there. 

    - This matches your statement "If a TCastleControl is dropped on a blank project it will result in the same Leak report as loading a gltf (so the GLTF ain't leaking from the look of it but TCastleControl is)" -- yeah, so memory leak of "blank project with TCastleControl on FMX form" was TUnicodeCharEqualityComparer

4. https://github.com/peardox/LeakTest with `usex3d` leaks stuff, seems to be around XML stuff (OK, makes sense, reading `knight.x3d` uses XML).

    - Note that it seems that switching to OmniXML (from MSXML) this weekend doesn't make any difference here. If you want to experiment with it, you can remove `{$define CASTLE_XML_OMNI}` in `src\compatibility\delphi-only\dom.pas` (for Windows and Delphi (not C++ Builder), this will work equally well as OmniXML).

OK, so in total we have 2 problems remaining:

- VCL specific: `ApplicationProperties.OnGLContextClose` never called, causes leaks

- XML related (occurs when reading X3D XML, probably also any other XML from CGE), reproducible with both OmniXML and MSXML, and both VCL and FMX.

**Comment by michaliskambi** [comment] 2023-11-27 00:22
> VCL specific: ApplicationProperties.OnGLContextClose never called, causes leaks

This is fixed now.

So only XML leak remains.

**Closed** 2023-11-27 00:53 UTC

**Comment by michaliskambi** [comment] 2023-11-27 00:55
> XML related (occurs when reading X3D XML, probably also any other XML from CGE), reproducible with both OmniXML and MSXML, and both VCL and FMX.

Also fixed :) So everything is fixed in all situations, tested using your https://github.com/peardox/LeakTest/ and our examples/delphi/vcl and examples/delphi/fmx .
