### ISSUE TITLE
Problems with StreamIO and Castle Engine

### ISSUE THREAD

**Issue by juegoenlazaruscr** [castle-engine/castle-engine#161] opened 2020-06-12 17:53 UTC
I am porting some old games of mine to Android and Linux 64 bits with CastleEngine on background to complete many taskts.

The following code works on Windows 64 and Android 32 bits... but it does not work on Windows 32 bit with CastleEngine 6.5 and fpc 3.0.4. It is important to me because my own style of programming with text files. 

uses
  Classes, SreamIO, CastleLog, ....

var
  CustomStream: TMemoryStream;
  MyText : Text;
  StringOriginal : String;
...
  CustomStream := TMemoryStream.Create;
  AssignStream( MyText, CustomStream );
  ReWrite( MyText );
  WriteLn( MyText, 'First line' );
  WriteLn( MyText, 'Second line' );
  WriteLn( MyText, 'Third line' );
  Close( MyText );
  Reset( MyText );
  CustomStream.Seek(0, soBeginning);
  ReadLn(MyText, STringOriginal);
  WriteLnLog(StringOriginal);
  ReadLn(MyText, STringOriginal);
  WriteLnLog(StringOriginal);
  ReadLn(MyText, STringOriginal);
  WriteLnLog(StringOriginal);
  Close( MyText );
  FreeANDNil(CustomStream);

With Windows 64 bit or Android 32 bits: this print on log:
First Line
Second Line
Third Line
But it does not work with Windows 32 bits. 
Similar code runs well on FreePascal without Castle Engine.

**Comment by michaliskambi** [comment] 2020-06-12 20:20
That is interesting. Looking over your code snippet, it doesn't use any CGE API (TMemoryStream, AssignStream etc. are all FPC routines) except `WriteLnLog`. So it should work the same with or without CGE -- using CGE doesn't change how the standard things work, I mean the code is still just compiled with FPC and should work the same.

Can you provide a complete (compileable) example code that I can run and test?

**Comment by juegoenlazaruscr** [comment] 2020-06-12 21:03
This example code is a trivial modification of the example: on portable_game_skeleton folder of Castle Engine distribution.
You will need the same data folder.
It includes a pure FreePascal version that runs without any problem.
In my first comment: I say that code works on Windows 64 but not on Windows 32 bits This is true, but when I test the next code that prepare for your response. It woks on Windows 32 bit and do not works on Windows 64 bits.... Just inverse of that I said on my first commentary. ¿¿...??

[FreePascal with Castle Engine]
{ Program to run the game on desktop (standalone) platforms.
  Can be auto-generated by "castle-engine generate-program". }
program my_fantastic_game_standalone;

{$ifdef MSWINDOWS} {$apptype GUI} {$endif}

{ This adds icons and version info for Windows,
  automatically created by "castle-engine compile". }
{$ifdef CASTLE_AUTO_GENERATED_RESOURCES} {$R castle-auto-generated-resources.res} {$endif}

uses CastleApplicationProperties, CastleLog, CastleWindow, GameInitialize;

begin
  { Optionally you can specify here your application version.
    It will appear e.g. in the log and in the --help output.
    Instead of updating this program file, you can also delete it (and remove
    "standalone_source" from the CastleEngineManifest.xml),
    and specify <version> inside CastleEngineManifest.xml.
    In this case, the program file, with appropriate version set,
    will be automatically generated and updated by the build tool. }
  ApplicationProperties.Version := '';
  Application.ParseStandardParameters;

  { On standalone, activate log only after parsing command-line options.
    This allows to handle --version and --help command-line parameters
    without any extra output on Unix. }
  InitializeLog;

  Application.MainWindow.OpenAndRun;
end.


{ Game initialization and logic.
  You will probably split larger games into more units,
  and then this main unit will just initialize everything else.

  This code is independent from mobile / standalone platforms.
  It will be used by the appropriate .lpr file for desktop, Android or iOS.

  Feel free to use this code as a starting point for your own projects.
  (This code is in public domain, unlike most other CGE code which
  is covered by the LGPL license variant, see the COPYING.txt file.) }
unit GameInitialize;

interface

implementation

uses SysUtils, Classes, StreamIO,
  CastleWindow, CastleScene, CastleControls, CastleLog,
  CastleFilesUtils, CastleSceneCore, CastleKeysMouse, CastleColors,
  CastleUIControls, CastleApplicationProperties;

var
  Window: TCastleWindow;
  Status: TCastleLabel;
  ExampleImage: TCastleImageControl;
  ExampleScene: TCastleScene;

{ routines ------------------------------------------------------------------- }

procedure WindowUpdate(Container: TUIContainer);
begin
  // ... do something every frame
  Status.Caption := 'FPS: ' + Container.Fps.ToString;
end;

procedure WindowPress(Container: TUIContainer; const Event: TInputPressRelease);
begin
  // ... react to press of key, mouse, touch
end;

{ One-time initialization of resources. }
procedure ApplicationInitialize;
var
  CustomStream : TMemoryStream;
  MyText : Text;
  StringOriginal : String;

begin
  { Assign Window callbacks }
  Window.OnUpdate := @WindowUpdate;
  Window.OnPress := @WindowPress;

  { For a scalable UI (adjusts to any window size in a smart way), use UIScaling }
  Window.Container.UIReferenceWidth := 1024;
  Window.Container.UIReferenceHeight := 768;
  Window.Container.UIScaling := usEncloseReferenceSize;

  { Show a label with frames per second information }
  Status := TCastleLabel.Create(Application);
  Status.Anchor(vpTop, -10);
  Status.Anchor(hpRight, -10);
  Status.Color := Yellow; // you could also use "Vector4(1, 1, 0, 1)" instead of Yellow
  Window.Controls.InsertFront(Status);

  { Show 2D image }
  ExampleImage := TCastleImageControl.Create(Application);
  ExampleImage.URL := 'castle-data:/example_image.png';
  ExampleImage.Bottom := 100;
  ExampleImage.Left := 100;
  Window.Controls.InsertFront(ExampleImage);

  { Show a 3D object (TCastleScene) inside a Window.SceneManager
    (which acts as a full-screen viewport by default). }
  ExampleScene := TCastleScene.Create(Application);
  ExampleScene.Load('castle-data:/example_scene.x3dv');
  ExampleScene.Spatial := [ssRendering, ssDynamicCollisions];
  ExampleScene.ProcessEvents := true;
  Window.SceneManager.Items.Add(ExampleScene);
  Window.SceneManager.MainScene := ExampleScene;

  WriteLnLog('This is my TEST:::');
  CustomStream := TMemoryStream.Create;
  AssignStream( MyText, CustomStream );
  ReWrite( MyText );
  WriteLn( MyText, 'This is first line' );
  WriteLn( MyText, 'second line' );
  WriteLn( MyText, 'third line' );
  Close( MyText );
  Reset(MyText);
  CustomStream.Seek(0, soBeginning);
  ReadLn(MyText, STringOriginal);
  WriteLnLog(StringOriginal);
  ReadLn(MyText, STringOriginal);
  WriteLnLog(StringOriginal);
  ReadLn(MyText, STringOriginal);
  WriteLnLog(StringOriginal);
  Close( MyText );
  FreeANDNil(CustomStream);
end;

initialization
  { Set ApplicationName early, as our log uses it.
    Optionally you could also set ApplicationProperties.Version here. }
  ApplicationProperties.ApplicationName := 'my_fantastic_game';

  { Start logging. Do this as early as possible,
    to log information and eventual warnings during initialization. }
  InitializeLog;

  { Initialize Application.OnInitialize. }
  Application.OnInitialize := @ApplicationInitialize;

  { Create and assign Application.MainWindow. }
  Window := TCastleWindow.Create(Application);
  Application.MainWindow := Window;

  { You should not need to do *anything* more in the unit "initialization" section.
    Most of your game initialization should happen inside ApplicationInitialize.
    In particular, it is not allowed to read files before ApplicationInitialize
    (in case of non-desktop platforms, some necessary may not be prepared yet). }
end.


[Only FreePascal version. It works OK.]

program project1;
{$mode objfpc}{$H+}
uses
  SysUtils, Classes, StreamIO;

var
  MyText : Text;
  StringOriginal : String;
  CustomStream : TMemoryStream;

begin
  CustomStream := TMemoryStream.Create;
  AssignStream( MyText, CustomStream );
  ReWrite( MyText );
  WriteLn( MyText, 'This is first line' );
  WriteLn( MyText, 'second line' );
  WriteLn( MyText, 'third line' );
  Close( MyText );
  Reset(MyText);
  CustomStream.Seek(0, soBeginning);
  ReadLn(MyText, STringOriginal);
  WriteLn(StringOriginal);
  ReadLn(MyText, STringOriginal);
  WriteLn(StringOriginal);
  ReadLn(MyText, STringOriginal);
  WriteLn(StringOriginal);
  Close( MyText );
  FreeANDNil(CustomStream);
end.

**Comment by michaliskambi** [comment] 2020-06-12 21:41
It works perfectly OK for me, with FPC 3.2.0 (FPC SVN fixes branch), on Windows 10, with 64-bit executable "Win64 / x86_64".

I'm using the very latest CGE 6.5 from https://castle-engine.io/ (your example seems to be based on an older portable_game_skeleton).

Here is the part of generated log:

```
Log for "my_fantastic_game".
  Started on 2020-06-12 at 23:35:24.
  Castle Game Engine version: 6.5 (unstable).
  Compiled with: FPC 3.2.0 (Win64 / x86_64), platform: Desktop.
[....]
This is my TEST:::
This is first line
second line
third line
```

I didn't try with win32 yet, but you say that it works OK on win32 and fails on win64 for you.

- What exactly FPC version do you use? 

- Can you try with FPC 3.2.0 (FPC SVN fixes branch) or last stable release FPC 3.0.4?

- Please clarify *how* does it "not work" for you. What exactly happens when you experience the problem -- crash, invalid output, what output?

**Comment by michaliskambi** [comment] 2020-06-12 21:53
I checked with win32, and it also works for me. The log shows:

```
Log for "my_fantastic_game".
  Started on 2020-06-12 at 23:52:02.
  Castle Game Engine version: 6.5 (unstable).
  Compiled with: FPC 3.2.0 (Win32 / i386), platform: Desktop.
[....]
This is my TEST:::
This is first line
second line
third line
```

There must be some difference in our environments. (I would suspect you use a different FPC version?)

**Comment by juegoenlazaruscr** [comment] 2020-06-12 22:34
I hope this is an old bug... corrected to future versions of freepascal.
FPC 3.0.4 (actual official version)
Lazarus 2.0.2.
This is the link to dropbox, with the Lazarus project files

https://www.dropbox.com/s/n6a6xqdatrduwxh/streamIO_castleTest.zip?dl=1

It includes your castle-fpc.cfg only for for reference...

**Comment by juegoenlazaruscr** [comment] 2020-06-12 22:37
Do not work... means a blank line...
NOTE: Some tests with CustomStream.ReadByte() works well... Information was writen to the Stream.

**Comment by michaliskambi** [comment] 2020-06-17 10:05
Tested with FPC 3.0.4 today.

I cannot reproduce it with FPC 3.0.4 either, on win32 and win64. This is the log output I get on win64:

```
Log for "my_fantastic_game".
  Started on 2020-06-17 at 11:08:59.
  Castle Game Engine version: 6.5 (unstable).
  Compiled with: FPC 3.0.4 (Win64 / x86_64), platform: Desktop.
[....]
This is my TEST:::
This is first line
second line
third line
```

And this is the log output on win32:

```
Log for "my_fantastic_game".
  Started on 2020-06-17 at 11:58:35.
  Castle Game Engine version: 6.5 (unstable).
  Compiled with: FPC 3.0.4 (Win32 / i386), platform: Desktop.
[...]
This is my TEST:::
This is first line
second line
third line
```

I run it a few times, but it is always correct for me.

So it's correct for me, on both win32 and win64, with both FPC 3.0.4 and FPC from latest fixes branch.

All testing was done on latest Windows 10, with latest CGE, I copied your code over `examples/portable_game_skeleton/gameinitialize.pas` and just compiled with CGE build tool, like

```
castle-engine compile 
```

(above is for for win64, which is the default since I used a build tool precompiled for win64) and

```
castle-engine compile --os=win32 --cpu=i386
```

(for win32).

There may be something else that is different between our environments. It's weird that is always works for me :) Please

- Try to test with latest FPC from their fixes_3_2 branch (it's trivial to install using e.g. fpcupdeluxe , https://github.com/castle-engine/castle-engine/wiki/fpcupdeluxe )

- Test with latest CGE from https://castle-engine.io/ . There *should not* be any change related to this (I cannot see how any code in CGE could make this wrong), but just in case :)

**Comment by juegoenlazaruscr** [comment] 2020-06-19 20:13
I have tried many times to install some fixes, but actually I am having problems. fpcupdeluxe is not working well for me. I am having some problems... I know it is pending a lot of methds to try...
I am going to try many times. Because of your independent tests I thing it is a fixed problem, My test with a totally renewed official version is not working.
Thanks for your help...
NOTE: Some times, could be useful a total cleaning of files with reference to fpc, lazarus, fpecupdeluxe, laz4android, castle engine and so. I do not know about this for fpc.

**Comment by michaliskambi** [comment] 2020-06-19 21:09
I'm going to close this then. It you will find any method that allows me to reproduce it (it can even be with old FPC, or old CGE -- anything that would allow me to investigate) please let me know by reopening this issue. For now, my summary is:

- Your testcase works OK for me, with both FPC 3.0.4 and latest FPC 3.2.0 (fixes_3_2 branch of FPC), on both win32 and win64.

- The code you have should be independent of CGE. So if there's is some problem, I would be surprised if it's related to CGE. StreamIO, TMemoryStream etc. are part of FPC, and using them with or without CGE should make no difference.

- If you have trouble installing latest FPC using fpcupdeluxe, you can submit it to https://github.com/LongDirtyAnimAlf/fpcupdeluxe/issues . The maintainer of fpcupdeluxe is very active and he can possibly help you easily.

**Closed by michaliskambi** 2020-06-19 21:09 UTC
Labels: pending feedback
