### ISSUE TITLE
In TCastleEdit  , how to input Chinese characters?

### ISSUE THREAD

**Issue by shenxh** [castle-engine/castle-engine#159] opened 2020-05-27 01:30 UTC
Hello ,
I am a Chinese developer. First of all, thank you for building such a great game engine.
After my test, I found that I could not input （not output） Chinese characters in the text box（TCastleEdit）, how to solve it? 
Thank you!

**Comment by michaliskambi** [comment] 2020-05-27 10:16
- As for output: You need to load a font with Chinese characters. See https://castle-engine.io/manual_text.php for description. Some examples show this (including Chinese chars) on https://github.com/castle-engine/castle-engine/tree/master/examples/fonts/test_local_characters .

- As for input: First of all write on what system are you testing (Windows, Linux, Android etc.)? There is a different input on every one. Also write do you use TCastleWindowBase or TCastleControlBase (on Lazarus form). 

    - Our TCastleWindowBase accesses native platform APIs, so it should "just work" (it works with various locales, like Polish characters)
    - And TCastleControlBase uses Lazarus LCL which in turn uses native platform APIs which also should "just work"..

    That said, they were not tested with Chinese input, so it's possible there's something missing at some point.

Thank you!

**Comment by michaliskambi** [comment] 2020-05-27 10:17
Ups, didn't want to close it yet:)

**Comment by shenxh** [comment] 2020-05-27 12:18
Thank you for your answer!

But the problem is not solved.

1. In Chinese Windows environment, I use TCastleWindowBase, the code is like the picture：
![1png](https://user-images.githubusercontent.com/9800605/83017417-3250a900-a056-11ea-85e8-d5f490a4b8a6.png)

2. The operation effect is as follows. You cannot enter Chinese characters, but only English characters
![3](https://user-images.githubusercontent.com/9800605/83018048-3cbf7280-a057-11ea-87c7-410832dde38a.png)

Thank you!

**Comment by michaliskambi** [comment] 2020-05-27 12:24
OK, and I see on the screenshot you're on Windows. I'll test it soon and will let you know.

**Comment by shenxh** [comment] 2020-05-27 13:36
> OK, and I see on the screenshot you're on Windows. I'll test it soon and will let you know.

Thank you!

**Comment by michaliskambi** [comment] 2020-06-09 02:08
I have reproduced it (I can configure my Polish Windows to input characters in simplified Chinese, and I see that they don't input in CGE correctly).

And I know what's wrong (our current WinAPI handling isn't prepared for such input) :)

I was working a few hours on it. Some things work (I can handle WM_UNICHAR and WM_CHAR send without WM_KEYDOWN), but so far this fails in practice to handle my test simplified Chinese input correctly. WinAPI seems to behave contrary to it's specification :) I'll keep working on it and let you know.

**Comment by michaliskambi** [comment] 2020-06-10 00:34
I made a few improvements to our international input handling for WinAPI, in https://github.com/castle-engine/castle-engine/commit/b66859e6e07e070098cbec51da57cbb581091109 . 

Now I need your help to test it :) It seems I cannot test Chinese input myself, so I'm going to ask you to do some tests :) 

`<not important details>`
( Why I cannot test it myself? Not sure. But all my input using "simplified Chinese" is reported as `?` (ASCII 63) by WinAPI. I mean it's not "unrenderable font glyphs", the input is really reported as question marks, so it's garbled somewhere internally. Possibly it just cannot work on Polish Windows, but will work when your whole Windows language is Chinese. )
`</end of not important details>`

Tests I would like you to do:

1. Get the latest engine version from GitHub, https://github.com/castle-engine/castle-engine/ . Or take the latest release from https://castle-engine.io/ (it will be created by Jenkins in a few hours since this comment).

2. Take the latest version of the example examples/fonts/test_local_characters/ that you have been already using. I already added there a simple test TCastleEdit instance.

3. Extend the example line (in `examples/fonts/test_local_characters/gameinitialize.pas`):

    ```
    AllCharacters.Add('你好世界');
    ```

    to include all Chinese characters you plan to input. You still have to list them there explicitly, so please list all that you plan to enter.

4. Compile and run the test_local_characters:

    - choose "Switch to external font (only Chinese chars)"
    - try to input a few Chinese characters in the edit box
    - please send me a screenshot, and also a log file after this run. Log file is generated in location described in https://castle-engine.io/manual_log.php . Just `C:\Users\<user-name>\AppData\Local\test_local_characters\test_local_characters.log` in this case.

5. Now go to `src/window/windows/castlewindow_winapi.inc`, find the line `{.$define CASTLE_WINAPI_UNICODE}`, and change it to `{$define CASTLE_WINAPI_UNICODE}` (IOW, I want you to define `CASTLE_WINAPI_UNICODE` now).

6. Repeat step 4 -- recompile and run test_local_characters, and please send new screenshot and get new log from this run.

Thank you!

**Comment by shenxh** [comment] 2020-06-26 02:06
Thank you! I will test it and report back to you.

**Comment by michaliskambi** [comment] 2020-11-29 19:52
I'm closing this for now due to inactivity. As explained above, I cannot easily test it myself -- I suspect that I would need a Windows with everything switched to Chinese. As far as I can tell, the code should be doing now "the right thing".

**Closed by michaliskambi** 2020-11-29 19:52 UTC
Labels: pending feedback
