### ISSUE TITLE
Errors about inflateValidate in zlib.dll on Win32

### ISSUE THREAD

**Issue by limelect** [castle-engine/castle-engine#489] opened 2023-05-13 06:14 UTC
running animate_bones_by_code 64 OK
But running animate_bones_by_code 32
While it is running getting this msg at the beginning
and then it runs
![image](https://github.com/castle-engine/castle-engine/assets/4199131/a5dd6b5e-f3fd-4a67-a53c-c0b23cd96367)

**Comment by limelect** [comment] 2023-05-13 06:58
So many problems all over not going to play with it anymore
So good luck.
I will download it when it matures

**Comment by michaliskambi** [comment] 2023-05-13 21:14
You also reported the issue of `inflateValidate` in `zlib.dll` in previous issue, my answer from there remains valid (see these comments: https://github.com/castle-engine/castle-engine/issues/475#issuecomment-1526523852 , https://github.com/castle-engine/castle-engine/issues/475#issuecomment-1528929390 ). You have incompatible DLLs on your system -- and one of them requires `inflateValidate` from `zlib.dll`. CGE doesn't ever open `zlib.dll` directly (we only open `zlib1.dll`) and it doesn't require `inflateValidate`, nor does any of our dependencies require `inflateValidate`.

Let me try to organize the suggested actions in the best order:

1. First of all, you will most likely solve it if you copy the appropriate DLLs into the project's folder (so 
they appear alongside the EXE file).

- The easiest way to do this for examples included in CGE (whether the ones in `examples/delphi/` or any other in `examples`) is to first open CGE editor, and compile the application using CGE editor. We then put the appropriate DLLs in place.

- Slightly more manual method to to this is to copy the libraries manually. 
    - For Win32: https://github.com/castle-engine/castle-engine/tree/master/tools/build-tool/data/external_libraries/i386-win32 
    - For Win64: https://github.com/castle-engine/castle-engine/tree/master/tools/build-tool/data/external_libraries/x86_64-win64 

2. Aside from it, search your global DLLs paths (like `c:/windows/system32` and `c:/windows/syswow64`) for files names like `zlib*.dll`, `libpng*.dll`, `*freetype*.dll`). Some software (not CGE) installed there incompatible versions of these libraries. Maybe it's a a result of a combination of some other software.

To be clear, this is not related to Delphi 10.2 compatibility -- which we solved, confirmed is OK, and neither me nor @peardox observed similar issues with Delphi 10.2 installation. 

As I cannot reproduce the issue, and noone else noted it so far either, I have to conclude it's somehow specific to your Windows system.

**Comment by peardox** [comment] 2023-05-16 05:53
Ooh - there's a thought - could add DLLs to #492 

Note: I'm not as familiar with the DLL deployment bit - I'll have to experiment

**Comment by michaliskambi** [comment] 2024-02-23 22:03
Latest CGE now includes a design-time menu that will automatically place appropriate DLL files alongside the EXE when building CGE project from Delphi IDE -- https://castle-engine.io/wp/2024/02/23/new-delphi-packages-organization-and-tools-castle-game-engine-menu-in-delphi-ide/ .

This constitutes a fix to this issue.

As explained in https://github.com/castle-engine/castle-engine/issues/475#issuecomment-1528929390 , https://github.com/castle-engine/castle-engine/issues/489#issuecomment-1546750796 , the submitted seems to have some incompatible DLLs (maybe installed system-wide by some other software). As noone else can reproduce the problem, we assume this is the culprit. 

Automatic deployment of DLLs we have now fixed this issue. No matter what DLLs you have, if you compile a CGE project (with `CastleEngineManifest.xml`, like any CGE example or new project created in CGE editor) the correct DLLs will be deployed alongside EXE and will hide any system DLLs that could be incompatible.

I'm not sure if the original submitter is still interested in this issue -- if you are, we'll appreciate a test with latest CGE.

**Closed** 2024-02-23 22:05 UTC
