### ISSUE TITLE
Weird blending (needs proper blending sorting)

### ISSUE THREAD

**Issue by Freedomax** [castle-engine/castle-engine#463] opened 2023-03-11 13:59 UTC
![GIF 2023-03-11 21-45-05](https://user-images.githubusercontent.com/26040454/224488417-e9fd8153-40b2-496f-a4e8-84491da11105.gif)

The rendering order of these three sprites is messed up.
 I modified the sprites of the two mages below, adding partially-transparent pixels. If I use the default 2D sprites, I don't have this problem. But my game sprites also have partially-transparent pixels, and the same problem occurs.

[my-new-project-2D-0.1-src.zip](https://github.com/castle-engine/castle-engine/files/10948659/my-new-project-2D-0.1-src.zip)

**Comment by Freedomax** [comment] 2023-03-15 12:53
I found this similar issue (in Godot):
 https://github.com/godotengine/godot-proposals/issues/3986.
Similar to the solution in unity:
https://github.com/godotengine/godot/pull/59404.

So CGE may need to add (in order of priority):

- `TSortLayer = Cardinal`
(layer 0 is built-in)

- `TSortOrder = integer`

- `TDepthOffset = single`

The tree structure of `TCastleTransform` is at the lowest priority.Eventually all `TShape` need to be sorted.
The combination of these three can complete the perfect 2D sorting.

**Comment by michaliskambi** [comment] 2023-04-25 22:56
( Sorry for delay with giving a precise answer to this. And I guess you already explored the reasons anyway, since you made https://github.com/castle-engine/castle-engine/pull/470  :) I want to comment here anyway, to share my thoughts for ideal solution. )

The problem here occurs because there's no good blending-sorting in CGE that would account for this situation. You have 3 scenes at various Z positions, but they are also in different places in TCastleTransform hierarchy graph. CGE has for now:

- Simple `MyViewport.Items.BlendingSort`, but it only sorts top-level `MyViewport.Items`
- You can manually use `TCastleTransform.SortBackToFront2D` or more general `TCastleTransform.SortBackToFront` on any `TCastleTransform`, but it is still not recursive.

But *we should* be able to just handle this case automatically. That is, I definitely want to solve this particular case in way that doesn't add a new API -- this situation should be handled perfectly by just setting `MyViewport.Items.BlendingSort` to `bs2D`.

The current `MyViewport.Items.BlendingSort` is much poorer, but it really should be better one day, as outlined in https://castle-engine.io/apidoc/html/CastleTransform.TCastleAbstractRootTransform.html#BlendingSort TODOs and in https://castle-engine.io/roadmap#shapes_across_scenes . I just expanded description and explanation of what I plan in the roadmap.

This is an important task, important "pain point" in CGE now, I know. People are bitten by poor support for blending sorting in CGE. Though I'm unsure if I'll make it before 7.0 release. But it should be then right after 7.0.

Note: This doesn't mean that I reject solutions to add some "manual" order, on top of Z. We already have https://castle-engine.io/apidoc/html/CastleTransform.TCastleTransform.html#RenderLayer , but it should be a number (not an enum with essentially 2 layer possible values), and it should be available at shapes (so also at Tiled layers). But in this particular case, I believe things can work "out of the box" in the future (well, if you set `MyViewport.Items.BlendingSort` to `bs2D`).

**Comment by Freedomax** [comment] 2023-04-26 08:46
But this problem has nothing to do with the hierarchy.

-  I modified the example, all 3 sprites are direct children of RootTransform, with sorting of RootTransform set to `bsNone`, but the problem still exists. 

![1](https://user-images.githubusercontent.com/26040454/234517282-ef8799e8-52f4-44fe-b2b5-895d29fe1d3a.gif)

- If all 3 sprites were semi-transparent, there wouldn't be a rendering issue.

![2](https://user-images.githubusercontent.com/26040454/234517479-191d9580-4b4b-4224-9c41-804ded6eff11.gif)

It's still an issue with the rendering order of **images with semi-transparent pixels** and **images without semi-transparent pixels**.

**Comment by michaliskambi** [comment] 2023-04-26 16:08
In my tests, if I put all scenes directly under `Viewport.Items`, and set `Viewport.Items.BlendingSort` to `bs2D` (note: not `bsNone`) this works OK. Objects with blending have correct order, also you can place objects without blending between them (at any Z values, even between 2 objects with blending) and they also work OK.

And it works OK then for both objects using blending (images with semi-transparent pixels) and not using blending (images without semi-transparent pixels).

Note that one has to use `bs2D`.

And it is true that problem is specific to objects with blending. For objects without blending, sorting isn't necessary, Z-buffer resolves them properly. The task https://castle-engine.io/roadmap#shapes_across_scenes affects "objects with blending" (which is equivalent "partially transparent objects" and "images with semi-transparent pixels", to make terminology clear :) ).

I'm attaching my test project, where I have made more drastic (to be visible) change to sprite textures to make them use blending, and also I have both sprite sheets with blending and without blending at the same time.

So from I can see, the "correct sorting by Z for objects using blending" is still the solution here. We just need to make `Viewport.Items.BlendingSort` better (as right now it only sorts whole scenes, and only scenes at top-level of `Viewport.Items` -- it should instead sort shapes, and work for scenes at any depth of hierarchy).

Can you point an arrangement of scenes in my test project where it fails?
[my-new-project-2D-0.1-src.zip](https://github.com/castle-engine/castle-engine/files/11334987/my-new-project-2D-0.1-src.zip)

![Zrzut ekranu z 2023-04-26 13-59-53](https://user-images.githubusercontent.com/1076978/234635697-6cc07b77-5ab0-4b4b-9a63-5f240de209ea.png)
![Zrzut ekranu z 2023-04-26 18-07-21](https://user-images.githubusercontent.com/1076978/234635703-8914e7cb-4456-4a8c-82f0-c5ef7c3304eb.png)

**Comment by Freedomax** [comment] 2023-04-30 00:18
I am increasingly convinced that using a 3D approach for a 2D game is not feasible, at least not for my current game type. The scene may contain thousands of objects, which may not run on some low-performance computers.

Also, I am closing this issue as it is already on the roadmap.

**Comment by michaliskambi** [comment] 2023-04-30 02:09
> I am increasingly convinced that using a 3D approach for a 2D game is not feasible, at least not for my current game type. The scene may contain thousands of objects, which may not run on some low-performance computers.
> 
> Also, I am closing this issue as it is already on the roadmap.

Let me reopen, and address some concerns :) 

The issue is valid and your testcase is valid. I'll want to close it only once roadmap https://castle-engine.io/roadmap#shapes_across_scenes is really done.

As for suitability for 2D and performance -- I believe we can make it good. Sorting by depth isn't really much different than sorting by some explicit value (like SortingLayer) and we can do it fast even for a lot of other objects. The choice is really between

A. we do some sorting
B. we rely that you provide items in already properly-sorted way.

The approach B is what practically happens now, and it will remain available when `BlendingSort` = `bsNone`, and as you can see -- it's really hard to work in case of non-trivial situation. 

So I want to follow A, make `Viewport.Items.BlendingSort` useful in more cases. We already use sorting for shapes within a single 3D scene, and I was testing it with lots of objects -- it wasn't a bottleneck yet.

Also, the previous sorting result can be cached -- meaning that in most typical case, when the sorting result from previous frame is still valid for new frame, there would not be much work except to validate previous list.

If you believe we could pursue some other solution, let me know. Looking at other engines, this is also what practically happens. Combination of sorting by depth, and sorting by some explicit parameter (you proposed https://github.com/castle-engine/castle-engine/pull/470/ , I'll probably go to rework our `RenderLayer` instead from enum->int, but the principle is the same).

**Comment by michaliskambi** [comment] 2023-04-30 03:26
I'll try to bump priority of https://castle-engine.io/roadmap#shapes_across_scenes , and do it ASAP -- it is important thing to do, and I want to show it makes sense for both 2D and 3D. If there will be performance issues in practice, I'm sure we'll be able to address them :)

**Comment by michaliskambi** [comment] 2023-05-04 18:53
I started working on proper blending sorting across all shapes. 

> B. we rely that you provide items in already properly-sorted way.

P.S. I feel I didn't clarify this. If you'd like to really "render things in the order they are specified":

- Leave `Viewport.Items.BlendingSort` = `bsNone`
- Treat all shapes, using blending and not using blending, the same way: just set `TNodeAppearance.AlphaMode` = to `amBlend` for all shapes.
- Finally, you can ignore the Z-buffer operations, set `RenderContext.DepthFunc = fdAlways`. We've had code doing exactly this in Tiled maps at one point -- `TCastleTiledMap.AssumePerfectRenderingOrder`. There are comments about this in https://github.com/castle-engine/castle-engine/blob/024802c94f356b7658ef98672e81d39304cb60dd/src/scene/load/x3dloadinternaltiledmap.pas#L328 -- basically, while it worked, it really means that everything must be in correct order. For complicated setups, this was difficult to work with -- although possible.

This is the ultimate combo to tell CGE "do not try to be smart about what is in front / back, just render things in the order I give you; items in Viewport.Items will be rendered in order you add them, shapes inside TCastleScene will be rendered in order you add them".

**Comment by Freedomax** [comment] 2023-05-05 02:16
`bsNone` is very important, and I don't use `bs2D` in the game at all because `bs2D` is tied to the Z coordinate, which the physics engine also depends on, causing confusion. Additionally, setting Z coordinates for a large number of objects can be cumbersome. I only use two types of sorting, `bsNone` and `bsYSort`.

It is very difficult to optimize based on multiple `TCastleScene`s currently. I need to store object information on the map tiles and then override `GetRenderList` and `Update` separately. If cross-scene batch processing is implemented, I think the optimization will be easier.

**Comment by michaliskambi** [comment] 2023-06-16 02:00
I got to this task this week.

Branch `shapes-rendering-2` ( https://github.com/castle-engine/castle-engine/tree/shapes-rendering-2 ) contains a big refactor of how shapes are rendered, allowing to mix all the shapes from different scenes. This

- Correctly sorts shapes using blending, no matter how are they organized in TCastleTransform hierarchy. So `Viewport.Items.BlendingSort` works how it was supposed to.

   This already solves the immediate problem from this issue. The `Viewport.Items.BlendingSort` = `bs2D` just makes rendering correct, making the visible order reflect the Z. It works regardless of how is this Z achieved (by any nesting of TCastleTransform), in the end the shapes will be sorted properly.

- Allows cross-scene batching, but this is in-progress now in that branch. For now batching is "under reconstruction" on that branch, code needs to be adjusted to account for new TCollectedShape type. But at least cross-scene batching *is* possible now, so we can have batching between e.g. TCastleScene(s) or TCastleImageTransform(s) if they render the same material/texture.

- Occlusion Query is also temporarily broken on this branch, occlusion query will have to change from per-scene to per-viewport specification to make sense most likely.

More work to follow, with the goal of course to merge this to master.

![Zrzut ekranu z 2023-06-16 03-55-23](https://github.com/castle-engine/castle-engine/assets/1076978/55d17808-ae2c-4358-8dae-3b0f3b9ba2df)

**Comment by michaliskambi** [comment] 2023-06-30 22:49
I have merged a big rendering refactor to CGE that addresses this.

Basically, by default, CGE now renders shapes using partial transparency (blending) correctly. Both testcases in this thread "just work correctly" when opened with latest CGE editor.

New property `Viewport.BlendingSort` allows to configure blending sort, and it is by default `sortAuto`, which automatically does correct 2D sorting when camera seems 2D.

There's also `Viewport.OcclusionSort`, and to address non-trivial cases we have `Viewport.OnCustomShapeSort` event.

More in https://castle-engine.io/wp/2023/06/30/big-renderer-improvements-correct-and-automatic-blending-sorting-more-powerful-batching-now-cross-scene-easier-and-more-reliable-occlusion-culling-and-occlusion-sorting/ .

**Closed by michaliskambi** 2023-06-30 22:49 UTC
